# Generated by Django 4.0.4 on 2022-09-17 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=500)),
                ('company_name', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('work_type', models.CharField(max_length=100)),
                ('total_vacancies', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=500)),
                ('required_skills', models.CharField(max_length=800)),
                ('work_description', models.TextField()),
                ('stars_needed', models.CharField(max_length=100)),
                ('validate_until', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_post_author', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
