# Generated by Django 4.0.4 on 2022-09-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0003_remove_jobmodel_category_jobmodel_sub_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobmodel',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='total_vacancies',
        ),
        migrations.RemoveField(
            model_name='jobmodel',
            name='work_type',
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
