# Generated by Django 4.0.4 on 2022-09-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0005_alter_jobmodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
