# Generated by Django 4.0.4 on 2022-09-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0006_rename_created_on_jobmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='budget',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
