# Generated by Django 4.0.4 on 2022-09-18 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0009_alter_offeredtodothejobmodel_offer_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='offeredtodothejobmodel',
            name='offer_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100),
        ),
    ]
