# Generated by Django 4.0.4 on 2022-09-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0010_offeredtodothejobmodel_offer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='job_attachments/'),
        ),
    ]
