# Generated by Django 4.0.4 on 2022-09-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_main', '0011_jobmodel_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Approved', 'Approved'), ('Selected', 'Selected'), ('Running', 'Running'), ('Submitted', 'Submitted'), ('Completed', 'Completed')], default='Requested', max_length=100),
        ),
    ]
