# Generated by Django 4.0.4 on 2022-09-17 14:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to='buyer_profile_picture/')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Enter Bangladeshi Number with country code', regex='^\\+?(88)01[3-9][0-9]{8}$')])),
                ('address', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=100)),
                ('member_since', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('Date_of_Birth', models.DateField(default='2000-01-01')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FreelancerProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='Freelancer_cover_image')),
                ('profile_picture', models.ImageField(upload_to='freelancer_profile_picture/')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Enter Bangladeshi Number with country code', regex='^\\+?(88)01[3-9][0-9]{8}$')])),
                ('Bkash_number', models.CharField(max_length=14, validators=[django.core.validators.RegexValidator(message='Enter Bangladeshi Number with country code', regex='^\\+?(88)01[3-9][0-9]{8}$')])),
                ('address', models.CharField(max_length=50)),
                ('what_you_are', models.CharField(max_length=100)),
                ('member_since', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('Date_of_Birth', models.DateField(default='2000-01-01')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('stars', models.IntegerField(default=0)),
                ('activity_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillListModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='App_auth.skillcategorymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skill_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LanguagesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laguage_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_languages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Extra_curricular_Activities_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=254)),
                ('perform_time', models.DateField(default='2000-01-01')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_extra_curricular', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExperiencesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('starting_year', models.DateField(default='2000-01-01')),
                ('leaving_year', models.DateField(blank=True, default='2000-01-01', null=True)),
                ('location', models.CharField(max_length=200)),
                ('Company', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_of_education', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
                ('institution', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Co_curricular_Activities_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=254)),
                ('perform_time', models.DateField(default='2000-01-01')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_co_curricular', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AchievementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=254)),
                ('perform_time', models.DateField(default='2000-01-01')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
