# Generated by Django 4.0.4 on 2022-09-18 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0002_buyerprofilemodel_user_freelancerprofilemodel_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyerprofilemodel',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='freelancerprofilemodel',
            old_name='User',
            new_name='user',
        ),
    ]
