# Generated by Django 4.0.4 on 2022-09-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0003_rename_user_buyerprofilemodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagesmodel',
            name='language_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expart', 'Expart')], default='Beginner', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skilllistmodel',
            name='skill_level',
            field=models.CharField(blank=True, choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Expart', 'Expart')], max_length=100, null=True),
        ),
    ]
