# Generated by Django 4.0.4 on 2022-09-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0004_languagesmodel_language_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillcategorymodel',
            name='logo',
            field=models.ImageField(blank=True, upload_to='category_logo/'),
        ),
    ]
