# Generated by Django 4.0.4 on 2022-09-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0005_skillcategorymodel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagesmodel',
            name='language_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Good For work', 'Good For work'), ('Native', 'Native')], max_length=100),
        ),
    ]
