# Generated by Django 4.0.4 on 2022-09-18 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0006_alter_languagesmodel_language_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyerprofilemodel',
            name='country',
            field=models.CharField(default='Banl', max_length=100),
        ),
    ]
