# Generated by Django 4.0.4 on 2022-09-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_auth', '0007_buyerprofilemodel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyerprofilemodel',
            name='country',
            field=models.CharField(default='Bangladesh', max_length=100),
        ),
    ]
